version: '2'
services:
    stormtrooper-app:
        image: stormtrooper
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://stormtrooper-mysql:3306/stormtrooper?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    stormtrooper-mysql:
        extends:
            file: mysql.yml
            service: stormtrooper-mysql
